name: pypi-publish

on:
  push:
    tags:
      - 'v*'

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Poetry
        uses: abatilo/actions-poetry@v2
        with:
          python_version: 3.8
          poetry_version: 1.1.13
          working_directory: ./
      - name: Poetry install
        run: poetry install
      - name: Poetry Publish
        run: poetry publish --build -u ${PYPI_USER} -p ${PYPI_PASSWORD}
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
