name: pythontests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.3
        working_directory: ./
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.3
        working_directory: ./python3
        args: run pytest -vvs
